theme = "catppuccin-frappe"
commit_order = "ascending"
comment_tab_width = 2
comment_vim = true
leader = " "
initial_commit_selection = "oldest"
single_file_view = true

comment_types = [
  { id = "note", label = "question", definition = "ask for clarification", color = "yellow" },
  { id = "suggestion", definition = "possible improvements", color = "blue" },
  { id = "issue", definition = "problems to fix", color = "orange" },
  { id = "praise", definition = "positive feedback", color = "green" },
  { id = "minor", label = "minor", definition = "small optional tweaks", color = "#d19a66" },
  { id = "nit", label = "nitpick", definition = "small optional tweaks", color = "#d19a66" },
]
